type: object
x-class-extra-annotation: "@lombok.AllArgsConstructor"
properties:
  caseOrApplicationReference:
    description: The case or application reference
    type: string
  arrestSummonsNumber:
    type: string
  applicationParticulars:
    type: string
  offences:
    description: The details of the offences for the defendant
    type: array
    minItems: 1
    items:
      $ref: './Offence.yaml'
  results:
    type: array
    minItems: 1
    items:
      $ref: './Result.yaml'
required:
  - caseOrApplicationReference
  - offences
